namespace: stark-monitor

redis:
  enabled: true

  image:
    repository: m.daocloud.io/docker.io/library/redis
    tag: "7-alpine"
    pullPolicy: IfNotPresent

  replicas: 1

  service:
    port: 6379

  persistence:
    enabled: true
    storageClass: local-path
    size: 1Gi

  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi