apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-controller
  namespace: stark-monitor
spec:
  replicas: 1

  selector:
    matchLabels:
      app: db-controller

  template:
    metadata:
      labels:
        app: db-controller

    spec:
      containers:
        - name: db-controller
          image: ghcr.io/king1039/zf-monitor-db-controller:latest
          imagePullPolicy: Always

          volumeMounts:
            - name: config
              mountPath: /app/config.yaml
              subPath: config.yaml
              readOnly: true

            - name: backend-data
              mountPath: /app/data

          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"

      volumes:
        - name: config
          secret:
            secretName: db-controller-config

        - name: backend-data
          hostPath:
            path: /opt/zf-monitor-docker-data/backend
            type: DirectoryOrCreate