image:
  repository: m.daocloud.io/docker.io/otel/opentelemetry-collector-contrib

mode: deployment

config:
  receivers:
    otlp:
      protocols:
        grpc: {}
        http: {}

  processors:
    batch: {}

  exporters:
    debug: {}

  service:
    pipelines:
      traces:
        receivers:
          - otlp
        processors:
          - batch
        exporters:
          - debug
