{{- if .Values.redis.enabled }}

apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: redis
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: {{ .Values.redis.service.port }}

---
{{- if .Values.redis.persistence.enabled }}

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.redis.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.redis.persistence.size }}

---
{{- end }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.redis.replicas }}

  selector:
    matchLabels:
      app: redis

  template:
    metadata:
      labels:
        app: redis

    spec:
      containers:
        - name: redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}

          args:
            - redis-server
            - --appendonly
            - "yes"

          ports:
            - containerPort: {{ .Values.redis.service.port }}

          resources:
{{ toYaml .Values.redis.resources | indent 12 }}

{{- if .Values.redis.persistence.enabled }}

          volumeMounts:
            - name: redis-data
              mountPath: /data

      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-data

{{- end }}

{{- end }}